"""
Django settings for assessment_disc_project project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# --- Segurança (habilitar em produção atrás de proxy/https) ---
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

from pathlib import Path
import os
from decouple import config, Csv
import dotenv

dotenv.load_dotenv()

SITE_ID = 1  # (corrige SITED_ID)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SITE_ID = 1 #para o allauth

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='dev-insecure-key')  # use var de ambiente em prod
DEBUG = config('DEBUG', default=True, cast=bool)

# Hosts permitidos (lista via env ou defaults úteis para Docker/WSL)
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,0.0.0.0',
    cast=Csv()
)

# Origem confiável para CSRF (necessário quando acessa via IP/porta no Docker)
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000,http://127.0.0.1:8000,http://0.0.0.0:8000',
    cast=Csv()
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',  # <-- necessário para allauth
    'crispy_forms',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'disc',
    'core',
    'user_auth',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',

]

ROOT_URLCONF = 'assessment_disc_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'assessment_disc_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Banco de dados: usa DATABASE_URL (Docker/prod) ou SQLite (dev)
# Exemplos de DATABASE_URL:
# - MySQL: mysql://user:password@db:3306/disc_assessment
# - Postgres: postgres://user:password@db:5432/disc_assessment
if config('DATABASE_URL', default=None):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(config('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


"""
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # padrão
    'user_auth.backends.CustomUserAuthBackend', # personalizado
]
"""
# Configuração do modelo de usuário customizado - OPCIONAL
#AUTH_USER_MODEL = 'user_auth.CustomUser'  # Substitua 'user_auth' pelo nome do seu app onde o CustomUser foi definido
AUTH_USER_MODEL = 'user_auth.CustomUser' #modo para colocar o allauth
LOGIN_REDIRECT_URL = 'user_auth:perfil'  # Ajuste o namespace e o nome da view conforme o definido no seu urls.py
ACCOUNT_SIGNUP_REDIRECT_URL = '/disc/teste_disc/' #para onde o usuario vai ser redirecionado depois de se cadastrar
ACCOUNT_EMAIL_VERIFICATION = 'none' #para não precisar confirmar o email

 #para onde o usuario vai ser redirecionado depois de logar

ACCOUNT_FORMS = {
    'signup': 'user_auth.forms.CustomAllauthSignupForm',
} #para usar o allauth, modelo dentro do user_auth/forms.py


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Adicione esta linha para definir onde os arquivos estáticos serão coletados
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Se você tem arquivos estáticos no seu projeto, adicione também:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


